// ── Query row shapes ──────────────────────────────────────────────────
// Hand-written companions to database.types.ts.
//
// IMPORTANT: nothing in this file may move into database.types.ts. That file
// is regenerated by `supabase gen types` and anything added to it is silently
// overwritten — which is exactly how these types were lost once already.
//
// `supabase gen types` only ever emits Database / Tables<> / Enums<>. It has
// no way to know about the embedded-resource selects in lib/data.ts, so the
// nested shapes below are declared by hand. Each type mirrors one select
// fragment in lib/data.ts:
//
//   • the table's own columns come from Pick<Tables<"...">, ...>, so column
//     types and nullability are always derived from the generated schema — a
//     regenerated schema shows up here as a compile error, never as a
//     runtime surprise;
//   • the relation keys are declared explicitly, because PostgREST returns
//     an embedded resource as a nested object (or array) rather than a column.
//
// A to-one embed is typed `| null`: PostgREST omits it when the row is
// missing, and `!inner` only guarantees non-null at the database level, not
// in the type system. The mappers in lib/data.ts already guard with `?.`.

import type { Tables } from "./database.types";

// ── Leaf rows (no embeds) ─────────────────────────────────────────────

/** `profiles ( id, role, name, slug, email, avatar )` */
export type ProfileRow = Pick<
  Tables<"profiles">,
  "id" | "role" | "name" | "slug" | "email" | "avatar"
>;

/** `skills` — the taxonomy catalog. */
export type SkillRow = Pick<
  Tables<"skills">,
  "id" | "name" | "domain" | "market_demand"
>;

export type CompanyRow = Pick<
  Tables<"companies">,
  "id" | "name" | "logo" | "industry" | "size" | "location"
>;

export type ProjectRow = Pick<
  Tables<"projects">,
  "id" | "title" | "description" | "tech_stack" | "url" | "verified"
>;

export type CertificationRow = Pick<
  Tables<"certifications">,
  "id" | "name" | "issuer" | "date" | "verified"
>;

export type LearningPathRow = Pick<
  Tables<"learning_paths">,
  "id" | "title" | "provider" | "url" | "duration" | "level" | "rating"
>;

// ── Rows with embedded resources ──────────────────────────────────────

/** `student_skills ( ..., skills ( name, domain ) )` */
export type StudentSkillRow = Pick<
  Tables<"student_skills">,
  "skill_id" | "level" | "verification" | "verified_at" | "verified_by"
> & {
  skills: Pick<Tables<"skills">, "name" | "domain"> | null;
};

/** `assessments ( ..., skills ( name ) )` */
export type AssessmentRow = Pick<
  Tables<"assessments">,
  "id" | "skill_id" | "score" | "max_score" | "level" | "date"
> & {
  skills: Pick<Tables<"skills">, "name"> | null;
};

/** Mirrors STUDENT_SELECT. */
export type StudentRow = Pick<
  Tables<"students">,
  | "id"
  | "degree"
  | "field"
  | "institution"
  | "year"
  | "gpa"
  | "bio"
  | "onboarding_complete"
> & {
  profiles: ProfileRow | null;
  student_skills: StudentSkillRow[];
  projects: ProjectRow[];
  certifications: CertificationRow[];
  assessments: AssessmentRow[];
};

/** Mirrors RECRUITER_SELECT. */
export type RecruiterRow = Pick<Tables<"recruiters">, "id" | "company_id"> & {
  profiles: ProfileRow | null;
};

/** `opportunity_skills ( ..., skills ( name ) )` */
export type OpportunitySkillRow = Pick<
  Tables<"opportunity_skills">,
  "skill_id" | "required_level" | "preferred"
> & {
  skills: Pick<Tables<"skills">, "name"> | null;
};

/** Mirrors OPPORTUNITY_SELECT. */
export type OpportunityRow = Pick<
  Tables<"opportunities">,
  | "id"
  | "title"
  | "company_id"
  | "recruiter_id"
  | "domain"
  | "description"
  | "eligibility"
  | "location"
  | "type"
  | "duration"
  | "compensation"
  | "deadline"
  | "posted_at"
  | "active"
> & {
  opportunity_skills: OpportunitySkillRow[];
};

/** Mirrors OPPORTUNITY_WITH_COMPANY_SELECT. */
export type OpportunityWithCompanyRow = OpportunityRow & {
  companies: CompanyRow | null;
};

/** Mirrors APPLICATION_SELECT. */
export type ApplicationRow = Pick<
  Tables<"applications">,
  "id" | "student_id" | "opportunity_id" | "current_stage" | "applied_at"
> & {
  application_stage_history: Pick<
    Tables<"application_stage_history">,
    "stage" | "occurred_at" | "note"
  >[];
};
